#!/bin/sh

#
# Installation script
#
# 1) cp uniprotload.config.default uniprotload.config
# 2) cp uniprotload.config.csh.default uniprotload.config.csh
# 3) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config files
MAIN_CONFIG=uniprotload.config

# Make sure config file exists and source it
if [ -r ${MAIN_CONFIG} ]
then
    echo "Source ${MAIN_CONFIG}"
    . ${MAIN_CONFIG}
else
    echo "Cannot source configuration file: ${MAIN_CONFIG}"
    installFailed
fi

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for each configuration file
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# Create the input directory if it doesn't exist.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi

